name: Azure Login Action
runs:
  using: composite 
  steps:
    - name: Az CLI login
      uses: azure/login@v2
      with: 
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false