apiVersion: v1
kind: Service
metadata:
  name: {{ include "helloworld.fullname" . }}
  annotations:
    #service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    {{- include "helloworld.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helloworld.selectorLabels" . | nindent 4 }}
