apiVersion: v1
kind: Pod
metadata:
  name: tfutil-pod
  labels:
    app: tfutil
spec:
  nodeName: aks-nd40rsv2-18247611-vmss000000
  containers:
  - name: tfutil-container
    image: cnagilla/tfutil:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
    command:
    - "/bin/bash"
    - "-c"
    - "sleep infinity"
  restartPolicy: Always
