name: Scheduled Build
on:
  schedule:
    - cron: '*/15 * * * *' # Runs every 5 minutes
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Date and Time
        run: |
          echo "Build Number: ${{ github.run_number }}"
          echo "Date: $(date '+%Y-%m-%d'), Time: $(date '+%H:%M:%S')"
